"""Frozen MBON side labels and the left-only POST-HOC RESCORING.

Decided 2026-09-22 (docs/design/open-decisions.md, item 2): the PRIMARY readout
uses all 96 MBON instances in both hemispheres, silent instances included.
**Left-hemisphere-only is a preregistered POST-HOC RESCORING** - never an arm, a
condition or a separate experiment. It is reported, it never gates a verdict, and
its decision margin would have to be calibrated separately on training data
because its units differ from the bilateral score.

What the rescoring can show depends on the experiment:

* First learning test: EXACT. Its teaching signal comes from the condition, not
  from the readout, so a left-only system would have run identical simulations and
  the rescoring coincides with what it would have done.
* Synthetic market: NOT exact. That loop is closed (score -> action -> teaching),
  so the rescoring reads the runs as they actually happened; it does not replay
  the decision loop and cannot show what a left-only system would have done.

The side table is frozen in ``data/mbon_sides_783.json`` (generated by
``repro/mushroom_body/prepare_mbon_sides.py`` from the pinned annotation
release). This module reads that JSON only - no pandas, no Brian2, no simulation.
The rescoring uses the per-MBON rates the runners save, so it adds no simulation.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple, Union

import numpy as np

from .readout import DEFAULT_AGGREGATION, ScoreResult, SignTable, circuit_score

DATA_DIR = Path(__file__).resolve().parent / "data"
SIDES_FILE = "mbon_sides_783.json"
LEFT = "left"
RIGHT = "right"


def load_mbon_sides(path: Optional[Union[str, Path]] = None) -> Dict[int, str]:
    """root_id -> side label, from the frozen table."""
    with open(Path(path) if path else DATA_DIR / SIDES_FILE) as fh:
        raw = json.load(fh)
    sides = {int(r["root_id"]): str(r["side"]) for r in raw["records"]}
    if len(sides) != len(raw["records"]):
        raise ValueError("duplicate root_id in the MBON side table")
    return sides


def side_mask(
    mbon_ids: Sequence[int],
    side: str = LEFT,
    sides: Optional[Dict[int, str]] = None,
) -> np.ndarray:
    """Boolean mask over ``mbon_ids`` selecting one hemisphere.

    Every ID must appear in the frozen table: an unknown MBON is an error, not a
    silent exclusion, because a silently dropped instance would change the mean.
    """
    table = load_mbon_sides() if sides is None else sides
    unknown = [int(i) for i in mbon_ids if int(i) not in table]
    if unknown:
        raise KeyError(f"{len(unknown)} MBON id(s) missing from the side table, e.g. {unknown[:3]}")
    return np.array([table[int(i)] == side for i in mbon_ids], dtype=bool)


def restrict_to_side(
    rates: Sequence[float],
    labels: Sequence[str],
    mbon_ids: Sequence[int],
    side: str = LEFT,
    sides: Optional[Dict[int, str]] = None,
) -> Tuple[np.ndarray, List[str]]:
    """``(rates, labels)`` kept for one hemisphere, in their original order."""
    r = np.asarray(rates, dtype=float)
    labels = list(labels)
    if r.shape != (len(labels),) or len(labels) != len(list(mbon_ids)):
        raise ValueError("rates, labels and mbon_ids must have the same length")
    mask = side_mask(mbon_ids, side, sides)
    return r[mask], [label for label, keep in zip(labels, mask.tolist()) if keep]


def one_side_score(
    rates: Sequence[float],
    labels: Sequence[str],
    mbon_ids: Sequence[int],
    table: SignTable,
    side: str = LEFT,
    aggregation: str = DEFAULT_AGGREGATION,
    sides: Optional[Dict[int, str]] = None,
) -> ScoreResult:
    """CIRCUIT score over one hemisphere's instances only (sensitivity check)."""
    kept_rates, kept_labels = restrict_to_side(rates, labels, mbon_ids, side, sides)
    return circuit_score(kept_rates, kept_labels, table, aggregation)
